
package pl.edu.pjwstk.tpr.jaxws.client.mtom;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BigDataStandard", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BigDataStandard {


    /**
     * 
     * @return
     *     returns pl.edu.pjwstk.tpr.jaxws.client.mtom.BigData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.mtom.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.mtom.GetResponse")
    @Action(input = "http://mtom.jaxws.tpr.pjwstk.edu.pl/BigDataStandard/getRequest", output = "http://mtom.jaxws.tpr.pjwstk.edu.pl/BigDataStandard/getResponse")
    public BigData get();

}
