
package pl.edu.pjwstk.tpr.jaxws.client.mtom;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BigDataMtomService", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", wsdlLocation = "http://localhost:8081/jax-ws-sample/big-data-mtom?wsdl")
public class BigDataMtomService
    extends Service
{

    private final static URL BIGDATAMTOMSERVICE_WSDL_LOCATION;
    private final static WebServiceException BIGDATAMTOMSERVICE_EXCEPTION;
    private final static QName BIGDATAMTOMSERVICE_QNAME = new QName("http://mtom.jaxws.tpr.pjwstk.edu.pl/", "BigDataMtomService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/jax-ws-sample/big-data-mtom?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIGDATAMTOMSERVICE_WSDL_LOCATION = url;
        BIGDATAMTOMSERVICE_EXCEPTION = e;
    }

    public BigDataMtomService() {
        super(__getWsdlLocation(), BIGDATAMTOMSERVICE_QNAME);
    }

    public BigDataMtomService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIGDATAMTOMSERVICE_QNAME, features);
    }

    public BigDataMtomService(URL wsdlLocation) {
        super(wsdlLocation, BIGDATAMTOMSERVICE_QNAME);
    }

    public BigDataMtomService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIGDATAMTOMSERVICE_QNAME, features);
    }

    public BigDataMtomService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BigDataMtomService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BigDataMtom
     */
    @WebEndpoint(name = "BigDataMtomPort")
    public BigDataMtom getBigDataMtomPort() {
        return super.getPort(new QName("http://mtom.jaxws.tpr.pjwstk.edu.pl/", "BigDataMtomPort"), BigDataMtom.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BigDataMtom
     */
    @WebEndpoint(name = "BigDataMtomPort")
    public BigDataMtom getBigDataMtomPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mtom.jaxws.tpr.pjwstk.edu.pl/", "BigDataMtomPort"), BigDataMtom.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIGDATAMTOMSERVICE_EXCEPTION!= null) {
            throw BIGDATAMTOMSERVICE_EXCEPTION;
        }
        return BIGDATAMTOMSERVICE_WSDL_LOCATION;
    }

}
