
package pl.edu.pjwstk.tpr.jaxws.client.mtom;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImageFilter", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImageFilter {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns pl.edu.pjwstk.tpr.jaxws.client.mtom.MyImage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createMyImage", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.mtom.CreateMyImage")
    @ResponseWrapper(localName = "createMyImageResponse", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.mtom.CreateMyImageResponse")
    @Action(input = "http://mtom.jaxws.tpr.pjwstk.edu.pl/ImageFilter/createMyImageRequest", output = "http://mtom.jaxws.tpr.pjwstk.edu.pl/ImageFilter/createMyImageResponse")
    public MyImage createMyImage(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<String> arg3);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "uploadImage", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.mtom.UploadImage")
    @ResponseWrapper(localName = "uploadImageResponse", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.mtom.UploadImageResponse")
    @Action(input = "http://mtom.jaxws.tpr.pjwstk.edu.pl/ImageFilter/uploadImageRequest", output = "http://mtom.jaxws.tpr.pjwstk.edu.pl/ImageFilter/uploadImageResponse")
    public void uploadImage(
        @WebParam(name = "arg0", targetNamespace = "")
        MyImage arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns pl.edu.pjwstk.tpr.jaxws.client.mtom.MyImage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.mtom.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.mtom.DownloadResponse")
    @Action(input = "http://mtom.jaxws.tpr.pjwstk.edu.pl/ImageFilter/downloadRequest", output = "http://mtom.jaxws.tpr.pjwstk.edu.pl/ImageFilter/downloadResponse")
    public MyImage download(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<pl.edu.pjwstk.tpr.jaxws.client.mtom.MyImage>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "filterList", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.mtom.FilterList")
    @ResponseWrapper(localName = "filterListResponse", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.mtom.FilterListResponse")
    @Action(input = "http://mtom.jaxws.tpr.pjwstk.edu.pl/ImageFilter/filterListRequest", output = "http://mtom.jaxws.tpr.pjwstk.edu.pl/ImageFilter/filterListResponse")
    public List<MyImage> filterList(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @return
     *     returns java.util.List<pl.edu.pjwstk.tpr.jaxws.client.mtom.MyImage>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.mtom.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.mtom.GetListResponse")
    @Action(input = "http://mtom.jaxws.tpr.pjwstk.edu.pl/ImageFilter/getListRequest", output = "http://mtom.jaxws.tpr.pjwstk.edu.pl/ImageFilter/getListResponse")
    public List<MyImage> getList();

}
