
package pl.edu.pjwstk.tpr.jaxws.client.mtom;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImageFilterService", targetNamespace = "http://mtom.jaxws.tpr.pjwstk.edu.pl/", wsdlLocation = "http://localhost:8081/jax-ws-sample/ImageFilter?wsdl")
public class ImageFilterService
    extends Service
{

    private final static URL IMAGEFILTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMAGEFILTERSERVICE_EXCEPTION;
    private final static QName IMAGEFILTERSERVICE_QNAME = new QName("http://mtom.jaxws.tpr.pjwstk.edu.pl/", "ImageFilterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/jax-ws-sample/ImageFilter?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMAGEFILTERSERVICE_WSDL_LOCATION = url;
        IMAGEFILTERSERVICE_EXCEPTION = e;
    }

    public ImageFilterService() {
        super(__getWsdlLocation(), IMAGEFILTERSERVICE_QNAME);
    }

    public ImageFilterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMAGEFILTERSERVICE_QNAME, features);
    }

    public ImageFilterService(URL wsdlLocation) {
        super(wsdlLocation, IMAGEFILTERSERVICE_QNAME);
    }

    public ImageFilterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMAGEFILTERSERVICE_QNAME, features);
    }

    public ImageFilterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImageFilterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImageFilter
     */
    @WebEndpoint(name = "ImageFilterPort")
    public ImageFilter getImageFilterPort() {
        return super.getPort(new QName("http://mtom.jaxws.tpr.pjwstk.edu.pl/", "ImageFilterPort"), ImageFilter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImageFilter
     */
    @WebEndpoint(name = "ImageFilterPort")
    public ImageFilter getImageFilterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mtom.jaxws.tpr.pjwstk.edu.pl/", "ImageFilterPort"), ImageFilter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMAGEFILTERSERVICE_EXCEPTION!= null) {
            throw IMAGEFILTERSERVICE_EXCEPTION;
        }
        return IMAGEFILTERSERVICE_WSDL_LOCATION;
    }

}
