
package pl.edu.pjwstk.tpr.jaxws.client.delayed;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SampleDelayedService", targetNamespace = "http://delayed.jaxws.tpr.pjwstk.edu.pl/", wsdlLocation = "http://localhost:8081/jax-ws-sample/sample-delayed?wsdl")
public class SampleDelayedService
    extends Service
{

    private final static URL SAMPLEDELAYEDSERVICE_WSDL_LOCATION;
    private final static WebServiceException SAMPLEDELAYEDSERVICE_EXCEPTION;
    private final static QName SAMPLEDELAYEDSERVICE_QNAME = new QName("http://delayed.jaxws.tpr.pjwstk.edu.pl/", "SampleDelayedService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/jax-ws-sample/sample-delayed?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAMPLEDELAYEDSERVICE_WSDL_LOCATION = url;
        SAMPLEDELAYEDSERVICE_EXCEPTION = e;
    }

    public SampleDelayedService() {
        super(__getWsdlLocation(), SAMPLEDELAYEDSERVICE_QNAME);
    }

    public SampleDelayedService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAMPLEDELAYEDSERVICE_QNAME, features);
    }

    public SampleDelayedService(URL wsdlLocation) {
        super(wsdlLocation, SAMPLEDELAYEDSERVICE_QNAME);
    }

    public SampleDelayedService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAMPLEDELAYEDSERVICE_QNAME, features);
    }

    public SampleDelayedService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SampleDelayedService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SampleDelayed
     */
    @WebEndpoint(name = "SampleDelayedPort")
    public SampleDelayed getSampleDelayedPort() {
        return super.getPort(new QName("http://delayed.jaxws.tpr.pjwstk.edu.pl/", "SampleDelayedPort"), SampleDelayed.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SampleDelayed
     */
    @WebEndpoint(name = "SampleDelayedPort")
    public SampleDelayed getSampleDelayedPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://delayed.jaxws.tpr.pjwstk.edu.pl/", "SampleDelayedPort"), SampleDelayed.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAMPLEDELAYEDSERVICE_EXCEPTION!= null) {
            throw SAMPLEDELAYEDSERVICE_EXCEPTION;
        }
        return SAMPLEDELAYEDSERVICE_WSDL_LOCATION;
    }

}
