
package pl.edu.pjwstk.tpr.jaxws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Filter", targetNamespace = "http://jaxws.tpr.pjwstk.edu.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Filter {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<pl.edu.pjwstk.tpr.jaxws.client.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSurnameFiltered", targetNamespace = "http://jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.GetSurnameFiltered")
    @ResponseWrapper(localName = "getSurnameFilteredResponse", targetNamespace = "http://jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.GetSurnameFilteredResponse")
    @Action(input = "http://jaxws.tpr.pjwstk.edu.pl/Filter/getSurnameFilteredRequest", output = "http://jaxws.tpr.pjwstk.edu.pl/Filter/getSurnameFilteredResponse")
    public List<Person> getSurnameFiltered(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<pl.edu.pjwstk.tpr.jaxws.client.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDateFiltered", targetNamespace = "http://jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.GetDateFiltered")
    @ResponseWrapper(localName = "getDateFilteredResponse", targetNamespace = "http://jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.GetDateFilteredResponse")
    @Action(input = "http://jaxws.tpr.pjwstk.edu.pl/Filter/getDateFilteredRequest", output = "http://jaxws.tpr.pjwstk.edu.pl/Filter/getDateFilteredResponse")
    public List<Person> getDateFiltered(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0);

}
