
package pl.edu.pjwstk.tpr.jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Sample", targetNamespace = "http://jaxws.tpr.pjwstk.edu.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Sample {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reply", targetNamespace = "http://jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.Reply")
    @ResponseWrapper(localName = "replyResponse", targetNamespace = "http://jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.ReplyResponse")
    @Action(input = "http://jaxws.tpr.pjwstk.edu.pl/Sample/replyRequest", output = "http://jaxws.tpr.pjwstk.edu.pl/Sample/replyResponse")
    public String reply(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
