
package pl.edu.pjwstk.tpr.jaxws.client.addressing;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddressingTargetService", targetNamespace = "http://addressing.jaxws.tpr.pjwstk.edu.pl/", wsdlLocation = "http://localhost:8081/jax-ws-sample/addressing-target?wsdl")
public class AddressingTargetService
    extends Service
{

    private final static URL ADDRESSINGTARGETSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDRESSINGTARGETSERVICE_EXCEPTION;
    private final static QName ADDRESSINGTARGETSERVICE_QNAME = new QName("http://addressing.jaxws.tpr.pjwstk.edu.pl/", "AddressingTargetService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/jax-ws-sample/addressing-target?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDRESSINGTARGETSERVICE_WSDL_LOCATION = url;
        ADDRESSINGTARGETSERVICE_EXCEPTION = e;
    }

    public AddressingTargetService() {
        super(__getWsdlLocation(), ADDRESSINGTARGETSERVICE_QNAME);
    }

    public AddressingTargetService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDRESSINGTARGETSERVICE_QNAME, features);
    }

    public AddressingTargetService(URL wsdlLocation) {
        super(wsdlLocation, ADDRESSINGTARGETSERVICE_QNAME);
    }

    public AddressingTargetService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDRESSINGTARGETSERVICE_QNAME, features);
    }

    public AddressingTargetService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddressingTargetService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddressingTarget
     */
    @WebEndpoint(name = "AddressingTargetPort")
    public AddressingTarget getAddressingTargetPort() {
        return super.getPort(new QName("http://addressing.jaxws.tpr.pjwstk.edu.pl/", "AddressingTargetPort"), AddressingTarget.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressingTarget
     */
    @WebEndpoint(name = "AddressingTargetPort")
    public AddressingTarget getAddressingTargetPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://addressing.jaxws.tpr.pjwstk.edu.pl/", "AddressingTargetPort"), AddressingTarget.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDRESSINGTARGETSERVICE_EXCEPTION!= null) {
            throw ADDRESSINGTARGETSERVICE_EXCEPTION;
        }
        return ADDRESSINGTARGETSERVICE_WSDL_LOCATION;
    }

}
