
package pl.edu.pjwstk.tpr.jaxws.client.addressing;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddressingCallback", targetNamespace = "http://addressing.jaxws.tpr.pjwstk.edu.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddressingCallback {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "replyAddressingCallback", targetNamespace = "http://addressing.jaxws.tpr.pjwstk.edu.pl/", className = "pl.edu.pjwstk.tpr.jaxws.client.addressing.ReplyAddressingCallback")
    @Action(input = "http://addressing.jaxws.tpr.pjwstk.edu.pl/AddressingCallback/replyAddressingCallback")
    public void replyAddressingCallback(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
