
package pl.edu.pjwstk.tpr.jaxws.client.onewayrobust;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OneWayRobust", targetNamespace = "http://onewayrobust.jaxws.tpo.glowacki.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OneWayRobust {


    /**
     * 
     * @param arg0
     * @throws TprException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "oneWayRobust", targetNamespace = "http://onewayrobust.jaxws.tpo.glowacki.eu/", className = "pl.edu.pjwstk.tpr.jaxws.client.onewayrobust.OneWayRobust_Type")
    @ResponseWrapper(localName = "oneWayRobustResponse", targetNamespace = "http://onewayrobust.jaxws.tpo.glowacki.eu/", className = "pl.edu.pjwstk.tpr.jaxws.client.onewayrobust.OneWayRobustResponse")
    @Action(input = "http://onewayrobust.jaxws.tpo.glowacki.eu/OneWayRobust/oneWayRobustRequest", output = "http://onewayrobust.jaxws.tpo.glowacki.eu/OneWayRobust/oneWayRobustResponse", fault = {
        @FaultAction(className = TprException_Exception.class, value = "http://onewayrobust.jaxws.tpo.glowacki.eu/OneWayRobust/oneWayRobust/Fault/TprException")
    })
    public void oneWayRobust(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws TprException_Exception
    ;

}
