
package pl.edu.pjwstk.tpr.jaxws.client.addressing;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddressingCallbackService", targetNamespace = "http://addressing.jaxws.tpr.pjwstk.edu.pl/", wsdlLocation = "http://localhost:8081/jax-ws-sample/addressing-callback?wsdl")
public class AddressingCallbackService
    extends Service
{

    private final static URL ADDRESSINGCALLBACKSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDRESSINGCALLBACKSERVICE_EXCEPTION;
    private final static QName ADDRESSINGCALLBACKSERVICE_QNAME = new QName("http://addressing.jaxws.tpr.pjwstk.edu.pl/", "AddressingCallbackService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/jax-ws-sample/addressing-callback?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDRESSINGCALLBACKSERVICE_WSDL_LOCATION = url;
        ADDRESSINGCALLBACKSERVICE_EXCEPTION = e;
    }

    public AddressingCallbackService() {
        super(__getWsdlLocation(), ADDRESSINGCALLBACKSERVICE_QNAME);
    }

    public AddressingCallbackService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDRESSINGCALLBACKSERVICE_QNAME, features);
    }

    public AddressingCallbackService(URL wsdlLocation) {
        super(wsdlLocation, ADDRESSINGCALLBACKSERVICE_QNAME);
    }

    public AddressingCallbackService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDRESSINGCALLBACKSERVICE_QNAME, features);
    }

    public AddressingCallbackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddressingCallbackService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddressingCallback
     */
    @WebEndpoint(name = "AddressingCallbackPort")
    public AddressingCallback getAddressingCallbackPort() {
        return super.getPort(new QName("http://addressing.jaxws.tpr.pjwstk.edu.pl/", "AddressingCallbackPort"), AddressingCallback.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressingCallback
     */
    @WebEndpoint(name = "AddressingCallbackPort")
    public AddressingCallback getAddressingCallbackPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://addressing.jaxws.tpr.pjwstk.edu.pl/", "AddressingCallbackPort"), AddressingCallback.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDRESSINGCALLBACKSERVICE_EXCEPTION!= null) {
            throw ADDRESSINGCALLBACKSERVICE_EXCEPTION;
        }
        return ADDRESSINGCALLBACKSERVICE_WSDL_LOCATION;
    }

}
